
USE master;
GO

-- Always On Availability Group Oluþturma
CREATE AVAILABILITY GROUP AG_Databaseproduct
    WITH (AUTOMATED_BACKUP_PREFERENCE = PRIMARY)
    FOR DATABASE Databaseproduct
    REPLICA ON
        N'DESKTOP-OATVGP8\MSSQLSERVER01' WITH (
            ENDPOINT_URL = 'TCP://DESKTOP-OATVGP8:5022',
            AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
            FAILOVER_MODE = AUTOMATIC,
            SEEDING_MODE = AUTOMATIC
        ),
        N'DESKTOP-OATVGP8\MSSQLSERVER02' WITH (
            ENDPOINT_URL = 'TCP://DESKTOP-OATVGP8:5023',
            AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
            FAILOVER_MODE = AUTOMATIC,
            SEEDING_MODE = AUTOMATIC
        );
GO
